GET http://localhost:8080/api/healthz

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I had something interesting kerfuffle for breakfast"
}


###
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I had something interesting for breakfast.I had something interesting for breakfast.I had something interesting for breakfast.I had something interesting for breakfast.I had something interesting for breakfast.I had something interesting for breakfast.I had something interesting for breakfastI had something interesting for breakfastI had something interesting for breakfastI had something interesting for breakfastI had something interesting for breakfast."
}
### 
POST http://localhost:8080/admin/reset
Content-Type: application/json

#### 

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "mloneusk@example.com"
}